apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  type: NodePort
  ports:
  - nodePort: 32080
    port: 8080
    targetPort: 8080
    protocol: TCP